### PR TITLE
building specific chronoboosts

### PR DESCRIPTION
**Pull request by jtsauls**
Adds unique chronoboost icons for protoss buildings and appropriate path references. 

Building image at 75% size was overlayed on chronoboost icon in bottom left corner at 90% opacity.

### CODE REVIEW

**Comment by pikiou** [comment]
It looks really cool!

**Comment by BurnySc2** [comment]
Thank you. It looks great.

Did you edit the images yourself, or where did you get them from?
I'm asking because of the MIT license and copyright.

**Comment by jtsauls** [comment]
I edited them myself. I was thinking that might be a little weird with the copyright. Fair use perhaps?

**Comment by jtsauls** [comment]
I don't think I can own those images, as they are just a combination of the icons in the repo that were owned by Blizzard. I renounce any ownership I would have, for what it's worth. 

I feel we're in the clear here most likely (no more egregious that using the blizzard's icons as already done).

**Comment by BurnySc2** [comment]
Oh yes, I forgot that they are originally owned by Blizzard.

The way you suggested sounds like the easiest solution. Thanks again!

**Review by BurnySc2 — APPROVED** [review]

**Pull request merged**
