### PR TITLE
More informative Terran add-on icons

### PR DESCRIPTION
**Pull request by jtsauls**
Changed the Lift/Land Terran building icons and tool tip, as well as the add-on image to be specific for each type of building.

### CODE REVIEW

**Comment by pikiou** [comment]
It looks great! I don't think these icons could be any better.

**Comment by jtsauls** [comment]
@BurnySc2 Do you have a chance to review this (and pikiou's other pull request)?

**Comment by BurnySc2** [comment]
I can look over it this weekend. It was a very stressful past 2 weeks for me.
Thanks to both of you for your work so far!

**Comment by pikiou** [comment]
If there is anything we can do to help, please tell us!
Till then, take care; life goes before sc2 planners :)

**Comment by jtsauls** [comment]
Agreed! Definitely rest before starcraft.

**Review by BurnySc2 — APPROVED** [review]

**Comment by BurnySc2** [comment]
Thank you for the changes!

**Pull request merged**
